#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

from _patch_utils import apply_file


PATCH_NAME = 'patch-blink-appdelegate-m'
TARGET = 'Blink/AppDelegate.m'
REPLACEMENTS = (
    (
        40,
        (
            '#include <libssh/callbacks.h>\n'
            '#include "xcall.h"\n'
            '#include "Blink-Swift.h"\n'
            '\n'
            '#ifdef BLINK_BUILD_ENABLED\n'
            'extern void build_auto_start_wg_ports(void);\n'
        ),
        (
            '#include <libssh/callbacks.h>\n'
            '#include "xcall.h"\n'
            '#include "Blink-Swift.h"\n'
            '#include <errno.h>\n'
            '#include <limits.h>\n'
            '#include <stdint.h>\n'
            '#include <stdio.h>\n'
            '#include <stdlib.h>\n'
            '#include <string.h>\n'
            '#include <unistd.h>\n'
            '#include <zlib.h>\n'
            '\n'
            '#ifdef BLINK_BUILD_ENABLED\n'
            'extern void build_auto_start_wg_ports(void);\n'
        ),
    ),
    (
        49,
        (
            '\n'
            '@import CloudKit;\n'
            '\n'
            '@interface AppDelegate () <UNUserNotificationCenterDelegate>\n'
            '@end\n'
            '\n'
        ),
        (
            '\n'
            '@import CloudKit;\n'
            '\n'
            'static uint16_t HermesReadLE16(const uint8_t *bytes) {\n'
            '  return (uint16_t)(bytes[0] | ((uint16_t)bytes[1] << 8));\n'
            '}\n'
            '\n'
            'static uint32_t HermesReadLE32(const uint8_t *bytes) {\n'
            '  return (uint32_t)bytes[0] | ((uint32_t)bytes[1] << 8) |\n'
            '         ((uint32_t)bytes[2] << 16) | ((uint32_t)bytes[3] << 24);\n'
            '}\n'
            '\n'
            'static BOOL HermesCRCMatches(const uint8_t *bytes, uint32_t length, uint32_t expected) {\n'
            '  uLong crc = crc32(0L, Z_NULL, 0);\n'
            '  uint32_t offset = 0;\n'
            '  while (offset < length) {\n'
            '    uint32_t chunkLength = MIN((uint32_t)UINT_MAX, length - offset);\n'
            '    crc = crc32(crc, bytes + offset, (uInt)chunkLength);\n'
            '    offset += chunkLength;\n'
            '  }\n'
            '  return (uint32_t)crc == expected;\n'
            '}\n'
            '\n'
            'static int64_t HermesRuntimeTimestamp(NSString *archivePath, BOOL verifyPayloads) {\n'
            '  NSData *archive = [NSData dataWithContentsOfFile:archivePath\n'
            '                                           options:NSDataReadingMappedIfSafe\n'
            '                                             error:nil];\n'
            '  if (archive.length < 22 || archive.length > UINT32_MAX) {\n'
            '    return -1;\n'
            '  }\n'
            '\n'
            '  const uint8_t *bytes = archive.bytes;\n'
            '  NSUInteger tailLength = MIN(archive.length, (NSUInteger)(22 + UINT16_MAX));\n'
            '  NSUInteger tailStart = archive.length - tailLength;\n'
            '  NSUInteger eocd = NSNotFound;\n'
            '  for (NSUInteger cursor = tailLength - 22 + 1; cursor > 0;) {\n'
            '    cursor--;\n'
            '    const uint8_t *candidate = bytes + tailStart + cursor;\n'
            '    if (HermesReadLE32(candidate) == 0x06054b50 &&\n'
            '        cursor + 22 + HermesReadLE16(candidate + 20) == tailLength) {\n'
            '      eocd = tailStart + cursor;\n'
            '      break;\n'
            '    }\n'
            '  }\n'
            '  if (eocd == NSNotFound) {\n'
            '    return -1;\n'
            '  }\n'
            '\n'
            '  const uint8_t *endRecord = bytes + eocd;\n'
            '  uint16_t entriesOnDisk = HermesReadLE16(endRecord + 8);\n'
            '  uint16_t totalEntries = HermesReadLE16(endRecord + 10);\n'
            '  uint32_t centralSize = HermesReadLE32(endRecord + 12);\n'
            '  uint32_t centralOffset = HermesReadLE32(endRecord + 16);\n'
            '  if (HermesReadLE16(endRecord + 4) != 0 || HermesReadLE16(endRecord + 6) != 0 ||\n'
            '      entriesOnDisk != totalEntries || totalEntries == UINT16_MAX ||\n'
            '      centralOffset > eocd || centralSize != eocd - centralOffset) {\n'
            '    return -1;\n'
            '  }\n'
            '\n'
            '  NSUInteger cursor = centralOffset;\n'
            '  NSUInteger centralEnd = cursor + centralSize;\n'
            '  NSUInteger timestampCount = 0;\n'
            '  NSUInteger entryCount = 0;\n'
            '  int64_t timestampValue = -1;\n'
            '  NSMutableSet<NSString *> *entryNames = [NSMutableSet setWithCapacity:totalEntries];\n'
            '  while (cursor < centralEnd) {\n'
            '    if (centralEnd - cursor < 46 || HermesReadLE32(bytes + cursor) != 0x02014b50) {\n'
            '      return -1;\n'
            '    }\n'
            '    const uint8_t *entry = bytes + cursor;\n'
            '    uint16_t flags = HermesReadLE16(entry + 8);\n'
            '    uint16_t method = HermesReadLE16(entry + 10);\n'
            '    uint32_t crc = HermesReadLE32(entry + 16);\n'
            '    uint32_t compressedSize = HermesReadLE32(entry + 20);\n'
            '    uint32_t uncompressedSize = HermesReadLE32(entry + 24);\n'
            '    uint16_t filenameLength = HermesReadLE16(entry + 28);\n'
            '    uint16_t extraLength = HermesReadLE16(entry + 30);\n'
            '    uint16_t commentLength = HermesReadLE16(entry + 32);\n'
            '    uint32_t localOffset = HermesReadLE32(entry + 42);\n'
            '    NSUInteger recordLength = 46 + filenameLength + extraLength + commentLength;\n'
            '    if (recordLength > centralEnd - cursor || filenameLength == 0 ||\n'
            '        method != 0 || compressedSize != uncompressedSize ||\n'
            '        (flags & 0x0009) != 0 || localOffset >= centralOffset ||\n'
            '        centralOffset - localOffset < 30 ||\n'
            '        HermesReadLE32(bytes + localOffset) != 0x04034b50) {\n'
            '      return -1;\n'
            '    }\n'
            '\n'
            '    NSString *name = [[NSString alloc] initWithBytes:entry + 46\n'
            '                                               length:filenameLength\n'
            '                                             encoding:NSUTF8StringEncoding];\n'
            '    if (name.length == 0 || [entryNames containsObject:name]) {\n'
            '      return -1;\n'
            '    }\n'
            '    [entryNames addObject:name];\n'
            '\n'
            '    const uint8_t *local = bytes + localOffset;\n'
            '    uint16_t localNameLength = HermesReadLE16(local + 26);\n'
            '    uint16_t localExtraLength = HermesReadLE16(local + 28);\n'
            '    NSUInteger localDataStart = (NSUInteger)localOffset + 30;\n'
            '    NSUInteger localHeaderRemainder = archive.length - localDataStart;\n'
            '    if (localNameLength != filenameLength ||\n'
            '        localNameLength > localHeaderRemainder ||\n'
            '        localExtraLength > localHeaderRemainder - localNameLength ||\n'
            '        memcmp(bytes + localDataStart, entry + 46, filenameLength) != 0 ||\n'
            '        HermesReadLE16(local + 6) != flags || HermesReadLE16(local + 8) != method ||\n'
            '        HermesReadLE32(local + 14) != crc ||\n'
            '        HermesReadLE32(local + 18) != compressedSize ||\n'
            '        HermesReadLE32(local + 22) != uncompressedSize) {\n'
            '      return -1;\n'
            '    }\n'
            '\n'
            '    NSUInteger dataOffset = localDataStart + localNameLength + localExtraLength;\n'
            '    if (dataOffset > centralOffset || compressedSize > centralOffset - dataOffset) {\n'
            '      return -1;\n'
            '    }\n'
            '    BOOL isTimestamp = [name isEqualToString:@"timestamp.txt"];\n'
            '    if (isTimestamp) {\n'
            '      timestampCount++;\n'
            '      if (timestampCount != 1 || uncompressedSize == 0 || uncompressedSize > 64) {\n'
            '        return -1;\n'
            '      }\n'
            '    }\n'
            '    if ((verifyPayloads || isTimestamp) &&\n'
            '        !HermesCRCMatches(bytes + dataOffset, uncompressedSize, crc)) {\n'
            '      return -1;\n'
            '    }\n'
            '    if (isTimestamp) {\n'
            '      NSString *text = [[NSString alloc] initWithBytes:bytes + dataOffset\n'
            '                                                length:uncompressedSize\n'
            '                                              encoding:NSASCIIStringEncoding];\n'
            '      NSString *trimmed = [text stringByTrimmingCharactersInSet:\n'
            '        [NSCharacterSet whitespaceAndNewlineCharacterSet]];\n'
            '      NSCharacterSet *nonDigits = [[NSCharacterSet characterSetWithCharactersInString:@"0123456789"] invertedSet];\n'
            '      if (trimmed.length == 0 || [trimmed rangeOfCharacterFromSet:nonDigits].location != NSNotFound) {\n'
            '        return -1;\n'
            '      }\n'
            '      unsigned long long parsed = strtoull(trimmed.UTF8String, NULL, 10);\n'
            '      if (parsed == 0 || parsed > INT64_MAX) {\n'
            '        return -1;\n'
            '      }\n'
            '      timestampValue = (int64_t)parsed;\n'
            '    }\n'
            '    cursor += recordLength;\n'
            '    entryCount++;\n'
            '  }\n'
            '  return entryCount == totalEntries && timestampCount == 1 ? timestampValue : -1;\n'
            '}\n'
            '\n'
            'static void InstallBundledHermesRuntime(void) {\n'
            '  NSBundle *bundle = [NSBundle mainBundle];\n'
            '  NSString *bundledPath = [bundle pathForResource:@"hermesrt" ofType:@"zip"];\n'
            '  NSString *homePath = [BlinkPaths hermesHomePath];\n'
            '  NSString *installedPath = [homePath stringByAppendingPathComponent:@"hermesrt.zip"];\n'
            '  if (bundledPath.length == 0) {\n'
            '    NSLog(@"Hermes runtime update skipped: bundled hermesrt.zip is missing");\n'
            '    return;\n'
            '  }\n'
            '\n'
            '  int64_t bundledTimestamp = HermesRuntimeTimestamp(bundledPath, NO);\n'
            '  int64_t installedTimestamp = HermesRuntimeTimestamp(installedPath, YES);\n'
            '  if (bundledTimestamp <= 0) {\n'
            '    NSLog(@"Hermes runtime update skipped: bundled timestamp.txt is invalid");\n'
            '    return;\n'
            '  }\n'
            '  if (installedTimestamp >= bundledTimestamp) {\n'
            '    NSLog(@"Hermes runtime kept: Documents/HermesHome/hermesrt.zip timestamp=%lld bundled=%lld",\n'
            '          (long long)installedTimestamp, (long long)bundledTimestamp);\n'
            '    return;\n'
            '  }\n'
            '\n'
            '  NSString *temporaryPath = [homePath stringByAppendingPathComponent:\n'
            '    [NSString stringWithFormat:@"hermesrt.zip.%@.tmp", NSUUID.UUID.UUIDString]];\n'
            '  NSError *error = nil;\n'
            '  NSFileManager *fileManager = [NSFileManager defaultManager];\n'
            '  if (![fileManager copyItemAtPath:bundledPath toPath:temporaryPath error:&error]) {\n'
            '    [fileManager removeItemAtPath:temporaryPath error:nil];\n'
            '    NSLog(@"Hermes runtime update failed while staging: %@", error.localizedDescription);\n'
            '    return;\n'
            '  }\n'
            '  if (HermesRuntimeTimestamp(temporaryPath, NO) != bundledTimestamp) {\n'
            '    [fileManager removeItemAtPath:temporaryPath error:nil];\n'
            '    NSLog(@"Hermes runtime update failed: staged ZIP timestamp does not match bundle");\n'
            '    return;\n'
            '  }\n'
            '  if (rename(temporaryPath.fileSystemRepresentation, installedPath.fileSystemRepresentation) != 0) {\n'
            '    int savedErrno = errno;\n'
            '    [fileManager removeItemAtPath:temporaryPath error:nil];\n'
            '    NSLog(@"Hermes runtime update failed while replacing archive: %s", strerror(savedErrno));\n'
            '    return;\n'
            '  }\n'
            '  NSLog(@"Hermes runtime installed from IPA: timestamp=%lld", (long long)bundledTimestamp);\n'
            '}\n'
            '\n'
            '@interface AppDelegate () <UNUserNotificationCenterDelegate>\n'
            '@end\n'
            '\n'
        ),
    ),
    (
        81,
        (
            '}\n'
            '\n'
            '- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {\n'
            '  \n'
            '  [Migrator perform];\n'
            '\n'
        ),
        (
            '}\n'
            '\n'
            '- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {\n'
            '  HermesLinkAppendLog("application didFinishLaunching");\n'
            '  \n'
            '  [Migrator perform];\n'
            '\n'
        ),
    ),
    (
        98,
        (
            '\n'
            '  sideLoading = false; // Turn off extra commands from iOS system\n'
            '  initializeEnvironment(); // initialize environment variables for iOS system\n'
            '  dispatch_async(bgQueue, ^{\n'
            '    addCommandList([[NSBundle mainBundle] pathForResource:@"blinkCommandsDictionary" ofType:@"plist"]); // Load blink commands to ios_system\n'
            '    __setupProcessEnv(); // we should call this after ios_system initializeEnvironment to override its defaults.\n'
            '    [AppDelegate _loadProfileVars];\n'
            '  });\n'
            '  \n'
            '  NSString *homePath = BlinkPaths.homePath;\n'
            '  setenv("HOME", homePath.UTF8String, 1);\n'
            '  setenv("SSH_HOME", homePath.UTF8String, 1);\n'
            '  setenv("CURL_HOME", homePath.UTF8String, 1);\n'
            '  \n'
            '  NSNotificationCenter *nc = NSNotificationCenter.defaultCenter;\n'
            '  [nc addObserver:self\n'
        ),
        (
            '\n'
            '  sideLoading = false; // Turn off extra commands from iOS system\n'
            '  initializeEnvironment(); // initialize environment variables for iOS system\n'
            '  addCommandList([[NSBundle mainBundle] pathForResource:@"blinkCommandsDictionary" ofType:@"plist"]); // Register app commands before Hermes can dispatch tools\n'
            '  dispatch_async(bgQueue, ^{\n'
            '    __setupProcessEnv(); // we should call this after ios_system initializeEnvironment to override its defaults.\n'
            '    [AppDelegate _loadProfileVars];\n'
            '  });\n'
            '  \n'
            '  // Use the real app Documents directory, which is exposed through Files and\n'
            '  // file sharing. Do not route Hermes through homePath/Documents: that path is\n'
            '  // a symlink created asynchronously and can become a private shadow folder.\n'
            '  NSString *documentsPath = [BlinkPaths documentsPath];\n'
            '  NSString *workspacePath = [documentsPath stringByAppendingPathComponent:@"workspace"];\n'
            '  [[NSFileManager defaultManager] createDirectoryAtPath:documentsPath\n'
            '                             withIntermediateDirectories:YES\n'
            '                                              attributes:nil\n'
            '                                                   error:nil];\n'
            '  [[NSFileManager defaultManager] createDirectoryAtPath:workspacePath\n'
            '                             withIntermediateDirectories:YES\n'
            '                                              attributes:nil\n'
            '                                                   error:nil];\n'
            '  NSString *hermesHomePath = [BlinkPaths hermesHomePath];\n'
            '  InstallBundledHermesRuntime();\n'
            '  NSString *homePath = BlinkPaths.homePath;\n'
            '  setenv("HOME", homePath.UTF8String, 1);\n'
            '  setenv("SSH_HOME", homePath.UTF8String, 1);\n'
            '  setenv("CURL_HOME", homePath.UTF8String, 1);\n'
            '  setenv("HERMES_HOME", hermesHomePath.UTF8String, 1);\n'
            '  setenv("HERMES_RUNTIME_ROOT", hermesHomePath.UTF8String, 1);\n'
            '  setenv("HERMES_WEBUI_DEFAULT_WORKSPACE", workspacePath.UTF8String, 1);\n'
            '  setenv("TERMINAL_CWD", workspacePath.UTF8String, 1);\n'
            '  setenv("PWD", workspacePath.UTF8String, 1);\n'
            '  chdir(workspacePath.UTF8String);\n'
            '  \n'
            '  NSNotificationCenter *nc = NSNotificationCenter.defaultCenter;\n'
            '  [nc addObserver:self\n'
        ),
    ),
)


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: patch-blink-appdelegate-m.py <blink-source-root>")
    apply_file(Path(sys.argv[1]).resolve(), TARGET, REPLACEMENTS, PATCH_NAME)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
